# Stash Config Make by Coldvvater
# TG Channel: https://t.me/Coldvvater_Channel
# GitHub: https://github.com/Coldvvater
# Update Date: 2024.08.18

# 通用设置
mode: rule
log-level: info
# DNS模块
dns:
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - system
  nameserver:
    - https://223.5.5.5/dns-query
    - https://120.53.53.53/dns-query
  fake-ip-filter:
    - .lan
    - cable.auth.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - network-test.debian.org
    - detectportal.firefox.com
    - resolver1.opendns.com
    - '*.srv.nintendo.net'
    - '*.stun.playstation.net'
    - xbox.*.microsoft.com
    - '*.xboxlive.com'
    - stun.*
    - global.turn.twilio.com
    - global.stun.twilio.com
    - localhost.*.qq.com
    - localhost.*.weixin.qq.com
    - '*.logon.battlenet.com.cn'
    - '*.logon.battle.net'
    - '*.blzstatic.cn'
    - music.163.com
    - '*.music.163.com'
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - '*.y.qq.com'
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - '*.xiami.com'
    - '*.music.migu.cn'
    - music.migu.cn
    - proxy.golang.org
    - '*.mcdn.bilivideo.cn'
    - '*.cmpassport.com'
    - id6.me
    - open.e.189.cn
    - mdn.open.wo.cn
    - opencloud.wostore.cn
    - auth.wosms.cn
    - '*.jegotrip.com.cn'
    - '*.icitymobile.mobi'
    - '*.pingan.com.cn'
    - '*.cmbchina.com'
    - pool.ntp.org
    - '*.pool.ntp.org'
    - ntp.*.com
    - ntp?.*.com
    - time.*.com
    - time?.*.com
    - time.*.gov
    - time.*.edu.cn
    - '*.ntp.org.cn'
    - PDC._msDCS.*.*
    - DC._msDCS.*.*
    - GC._msDCS.*.*
    # 服务提供商:
proxy-providers:
  Subscribe:
    url: http://your-service-provider # 用你的订阅链接替换
    interval: 86400
    benchmark-url: http://cp.cloudflare.com
    benchmark-timeout: 5
    # 功能分组
proxy-groups:
  - name: Final
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Final.png
    proxies:
      - Proxy
      - DIRECT
  - name: Proxy
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Rocket.png
    proxies:
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
      - DIRECT
  - name: AIGC
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/ChatGPT.png
    proxies:
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
  - name: YouTube
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/YouTube.png
    proxies:
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
  - name: NETFLIX
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Netflix.png
    proxies:
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
  - name: Emby
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Emby.png
    proxies:
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
      - DIRECT
  - name: BiliBili
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/bilibili_3.png
    proxies:
      - DIRECT
      - HongKong
      - TaiWan
  - name: Spotify
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Spotify.png
    proxies:
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
      - DIRECT
  - name: NetEaseMusic
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Netease_Music.png
    proxies:
      - DIRECT
  - name: TikTok
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/TikTok.png
    proxies:
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
  - name: Streaming
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Streaming.png
    proxies:
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
  - name: Telegram
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Telegram_X.png
    proxies:
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
  - name: X
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/X.png
    proxies:
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
  - name: Apple
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Apple_1.png
    proxies:
      - DIRECT
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
  - name: Google
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Google_Search.png
    proxies:
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
      - DIRECT
  - name: Microsoft
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Windows_11.png
    proxies:
      - DIRECT
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
  - name: Games
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Game.png
    proxies:
      - Proxy
      - HongKong
      - TaiWan
      - Japan
      - Korea
      - Singapore
      - America
      - UnitedKingdom
      - AllServer
      - DIRECT
  # 基于地区分组
  - name: HongKong
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png
    proxies:
      - HK-Auto
      - HK-FallBack
      - HK-LoadBalance
  - name: TaiWan
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/China.png
    proxies:
      - TW-Auto
      - TW-FallBack
      - TW-LoadBalance
  - name: Japan
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Japan.png
    proxies:
      - JP-Auto
      - JP-FallBack
      - JP-LoadBalance
  - name: Korea
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Korea.png
    proxies:
      - KR-Auto
      - KR-FallBack
      - KR-LoadBalance
  - name: Singapore
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Singapore.png
    proxies:
      - SG-Auto
      - SG-FallBack
      - SG-LoadBalance
  - name: America
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/United_States.png
    proxies:
      - US-Auto
      - US-FallBack
      - US-LoadBalance
  - name: UnitedKingdom
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/United_Kingdom.png
    proxies:
      - UK-Auto
      - UK-FallBack
      - UK-LoadBalance
  - name: AllServer
    type: select
    icon: https://raw.gitmirror.com/Koolson/Qure/master/IconSet/Color/Airport.png
    include-all: true
    filter: ^(?=.*(.))(?!.*((?i)群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|(\b(USE|USED|TOTAL|Traffic|Expire|EMAIL|Panel|Channel|Author)\b|(\d{4}-\d{2}-\d{2}|\d+G)))).*$
  - name: HK-Auto
    type: url-test
    hidden: true
    include-all: true
    filter: 港|🇭🇰|HK|(?i)Hong
    interval: 300
    lazy: true
  - name: TW-Auto
    type: url-test
    hidden: true
    include-all: true
    filter: 台|🇨🇳|🇹🇼|湾|TW|(?i)Taiwan
    interval: 300
    lazy: true
  - name: JP-Auto
    type: url-test
    hidden: true
    include-all: true
    filter: 日|🇯🇵|东京|JP|(?i)Japan
    interval: 300
    lazy: true
  - name: KR-Auto
    type: url-test
    hidden: true
    include-all: true
    filter: 韓|🇰🇷|韩国|KR|Korea
    interval: 300
    lazy: true
  - name: SG-Auto
    type: url-test
    hidden: true
    include-all: true
    filter: 新加坡|坡|狮城|🇸🇬|SG|(?i)Singapore
    interval: 300
    lazy: true
  - name: US-Auto
    type: url-test
    hidden: true
    include-all: true
    filter: 美|🇺🇲|US|(?i)States|American
    interval: 300
    lazy: true
  - name: UK-Auto
    type: url-test
    hidden: true
    include-all: true
    filter: 英|🇬🇧|英国|UK|United Kingdom
    interval: 300
    lazy: true
  - name: HK-FallBack
    type: fallback
    hidden: true
    include-all: true
    filter: 港|🇭🇰|HK|(?i)Hong
    interval: 300
    lazy: true
  - name: TW-FallBack
    type: fallback
    hidden: true
    include-all: true
    filter: 台|🇨🇳|🇹🇼|湾|TW|(?i)Taiwan
    interval: 300
    lazy: true
  - name: JP-FallBack
    type: fallback
    hidden: true
    include-all: true
    filter: 日|🇯🇵|东京|JP|(?i)Japan
    interval: 300
    lazy: true
  - name: KR-FallBack
    type: fallback
    hidden: true
    include-all: true
    filter: 韓|🇰🇷|韩国|KR|Korea
    interval: 300
    lazy: true
  - name: SG-FallBack
    type: fallback
    hidden: true
    include-all: true
    filter: 新加坡|坡|狮城|🇸🇬|SG|(?i)Singapore
    interval: 300
    lazy: true
  - name: US-FallBack
    type: fallback
    hidden: true
    include-all: true
    filter: 美|🇺🇲|US|(?i)States|American
    interval: 300
    lazy: true
  - name: UK-FallBack
    type: fallback
    hidden: true
    include-all: true
    filter: 英|🇬🇧|英国|UK|United Kingdom
    interval: 300
    lazy: true
  - name: HK-LoadBalance
    type: load-balance
    hidden: true
    include-all: true
    filter: 港|🇭🇰|HK|(?i)Hong
    strategy: consistent-hashing
    interval: 300
    lazy: true
  - name: TW-LoadBalance
    type: load-balance
    hidden: true
    include-all: true
    filter: 台|🇨🇳|🇹🇼|湾|TW|(?i)Taiwan
    strategy: consistent-hashing
    interval: 300
    lazy: true
  - name: JP-LoadBalance
    type: load-balance
    hidden: true
    include-all: true
    filter: 日|🇯🇵|东京|JP|(?i)Japan
    strategy: consistent-hashing
    interval: 300
    lazy: true
  - name: KR-LoadBalance
    type: load-balance
    hidden: true
    include-all: true
    filter: 韓|🇰🇷|韩国|KR|Korea
    strategy: consistent-hashing
    interval: 300
    lazy: true
  - name: SG-LoadBalance
    type: load-balance
    hidden: true
    include-all: true
    filter: 新加坡|坡|狮城|🇸🇬|SG|(?i)Singapore
    strategy: consistent-hashing
    interval: 300
    lazy: true
  - name: US-LoadBalance
    type: load-balance
    hidden: true
    include-all: true
    filter: 美|🇺🇲|US|(?i)States|American
    strategy: consistent-hashing
    interval: 300
    lazy: true
  - name: UK-LoadBalance
    type: load-balance
    hidden: true
    include-all: true
    filter: 英|🇬🇧|英国|UK|United Kingdom
    strategy: consistent-hashing
    interval: 300
    lazy: true
    # 规则引用
rules:
  - DOMAIN,raw.gitmirror.com,Proxy
  - RULE-SET,private-domain,DIRECT
  - RULE-SET,ai-classical,AIGC
  - RULE-SET,youtube-domain,YouTube
  - RULE-SET,netflix-domain,NETFLIX
  - RULE-SET,emby-classical,Emby
  - RULE-SET,bahamut-domain,TaiWan
  - RULE-SET,biliintl-domain,Streaming
  - RULE-SET,bilibili-domain,BiliBili
  - RULE-SET,spotify-domain,Spotify
  - RULE-SET,neteasemusic-classical,NetEaseMusic
  - RULE-SET,tiktok-domain,TikTok
  - RULE-SET,streamingmedia-classical,Streaming
  - RULE-SET,telegram-domain,Telegram
  - RULE-SET,github-domain,Proxy
  - RULE-SET,twitter-domain,X
  - RULE-SET,apple-classical,Proxy
  - RULE-SET,apple-domain,Apple
  - RULE-SET,google-domain,Google
  - RULE-SET,microsoft-domain,Microsoft
  - RULE-SET,games-classical,Games
  - RULE-SET,proxy-domain,Proxy
  - RULE-SET,google-ip,Google
  - RULE-SET,netflix-ip,NETFLIX
  - RULE-SET,telegram-ip,Telegram
  - RULE-SET,twitter-ip,X
  - RULE-SET,cn-domain,DIRECT
  - RULE-SET,bilibili-ip,BiliBili
  - RULE-SET,apple-ip,Apple
  - RULE-SET,private-ip,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Final
rule-providers:
  private-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.list
  private-ip:
    behavior: ipcidr
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.list
  ai-classical:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/Coldvvater/Mononoke/master/Clash/RuleSet/AI.list
  youtube-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.list
  netflix-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.list
  netflix-ip:
    behavior: ipcidr
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.list
  emby-classical:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/Repcz/Tool/X/Surge/Rules/Emby.list
  bahamut-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bahamut.list
  biliintl-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/biliintl.list
  bilibili-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.list
  bilibili-ip:
    behavior: ipcidr
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/bilibili.list
  spotify-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.list
  neteasemusic-classical:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.list
  tiktok-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.list
  streamingmedia-classical:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list
  telegram-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.list
  telegram-ip:
    behavior: ipcidr
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.list
  github-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.list
  twitter-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.list
  twitter-ip:
    behavior: ipcidr
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.list
  apple-classical:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/Coldvvater/Mononoke/master/Clash/RuleSet/AppleProxyService.list
  apple-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.list
  apple-ip:
    behavior: ipcidr
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.list
  google-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.list
  google-ip:
    behavior: ipcidr
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.list
  microsoft-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.list
  games-classical:
    behavior: classical
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.list
  cn-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geosite/cn.list
  proxy-domain:
    behavior: domain
    format: text
    interval: 86400
    url: https://raw.gitmirror.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.list
